"""add_llm_and_rag_trace_fields

Revision ID: 685da8fe2597
Revises: ac4fa394c551
Create Date: 2026-02-16 07:20:04.578986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685da8fe2597'
down_revision: Union[str, Sequence[str], None] = 'ac4fa394c551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_traces', sa.Column('llm_prompt', sa.Text(), nullable=True))
    op.add_column('agent_traces', sa.Column('llm_response_raw', sa.Text(), nullable=True))
    op.add_column('agent_traces', sa.Column('llm_model', sa.String(length=50), nullable=True))
    op.add_column('agent_traces', sa.Column('llm_temperature', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('agent_traces', sa.Column('llm_tokens_used', sa.Integer(), nullable=True))
    op.add_column('agent_traces', sa.Column('rag_query', sa.Text(), nullable=True))
    op.add_column('agent_traces', sa.Column('rag_scores', sa.JSON(), nullable=True))
    op.add_column('agent_traces', sa.Column('fallback_reason', sa.String(length=200), nullable=True))
    op.add_column('agent_traces', sa.Column('error_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_traces', 'error_details')
    op.drop_column('agent_traces', 'fallback_reason')
    op.drop_column('agent_traces', 'rag_scores')
    op.drop_column('agent_traces', 'rag_query')
    op.drop_column('agent_traces', 'llm_tokens_used')
    op.drop_column('agent_traces', 'llm_temperature')
    op.drop_column('agent_traces', 'llm_model')
    op.drop_column('agent_traces', 'llm_response_raw')
    op.drop_column('agent_traces', 'llm_prompt')
    # ### end Alembic commands ###
