"""add_analysis_state_to_transaction_records

Revision ID: ac4fa394c551
Revises: 
Create Date: 2026-02-13 20:35:49.673627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4fa394c551'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_records', sa.Column('analysis_state', sa.JSON(), nullable=True, comment='Complete OrchestratorState with all agent outputs'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_records', 'analysis_state')
    # ### end Alembic commands ###
