"""Decision and explanation models for the fraud analysis pipeline."""

from typing import Literal

from pydantic import BaseModel, ConfigDict, field_validator

DecisionType = Literal["APPROVE", "CHALLENGE", "BLOCK", "ESCALATE_TO_HUMAN"]


class FraudDecision(BaseModel):
    """Final fraud decision produced by the Decision Arbiter agent."""

    transaction_id: str
    decision: DecisionType
    confidence: float
    signals: list[str]
    citations_internal: list[dict]
    citations_external: list[dict]
    explanation_customer: str
    explanation_audit: str
    agent_trace: list[str]

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        if not 0.0 <= v <= 1.0:
            raise ValueError("confidence must be between 0.0 and 1.0")
        return v

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "transaction_id": "T-1001",
                "decision": "CHALLENGE",
                "confidence": 0.72,
                "signals": ["high_amount", "off_hours", "policy_match_FP-01"],
                "citations_internal": [
                    {"policy_id": "FP-01", "text": "Transacciones nocturnas > 3x promedio"}
                ],
                "citations_external": [
                    {"source": "merchant_watchlist", "detail": "No threats found"}
                ],
                "explanation_customer": "Hemos detectado actividad inusual en su cuenta. "
                "Por seguridad, necesitamos verificar esta transacción.",
                "explanation_audit": "Transacción T-1001 por S/1800 a las 03:15 excede 3.6x el promedio. "
                "Match con política FP-01. Debate: pro-fraud 0.78 vs pro-customer 0.55. "
                "Decisión CHALLENGE con confianza 0.72.",
                "agent_trace": [
                    "transaction_context",
                    "behavioral_pattern",
                    "policy_rag",
                    "external_threat",
                    "evidence_aggregation",
                    "debate_pro_fraud",
                    "debate_pro_customer",
                    "decision_arbiter",
                    "explainability",
                ],
            }
        }
    )


class ExplanationResult(BaseModel):
    """Explanation generated by the Explainability agent."""

    customer_explanation: str
    audit_explanation: str

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "customer_explanation": "Hemos detectado actividad inusual en su cuenta. "
                "Por seguridad, necesitamos verificar esta transacción.",
                "audit_explanation": "Transacción T-1001 analizada por 9 agentes. "
                "Riesgo compuesto: 68.5/100 (high). Debate adversarial: "
                "pro-fraud 0.78 vs pro-customer 0.55. Decisión: CHALLENGE (0.72).",
            }
        }
    )
